#!/usr/bin/env bash
set -euo pipefail

RULE_FILE="/etc/udev/rules.d/99-robot-lidar.rules"
LIDAR_LINK="ttyLidar"
LIDAR_DEV=""
LIST_ONLY=false

usage() {
  cat <<'EOF'
Usage:
  setup_lidar_udev.sh --list
  setup_lidar_udev.sh --device /dev/ttyUSB0 [options]

Options:
  --device <path>         Lidar serial device (e.g. /dev/ttyUSB0, /dev/ttyACM0)
  --link <name>           udev symlink name (default: ttyLidar)
  --rule-file <path>      udev rules output path (default: /etc/udev/rules.d/99-robot-lidar.rules)
  --list                  Print candidate tty devices and properties
  -h, --help              Show this help

Notes:
  - Rule priority: ID_VENDOR_ID + ID_MODEL_ID + ID_SERIAL_SHORT
    Fallback: ID_PATH (when ID_SERIAL_SHORT is not available)
  - The script applies rules via sudo if needed.
EOF
}

die() {
  echo "[ERROR] $*" >&2
  exit 1
}

log() {
  echo "[INFO] $*"
}

run_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

get_prop() {
  local dev="$1"
  local key="$2"
  udevadm info -q property -n "$dev" | awk -F= -v k="$key" '$1 == k {print $2; exit}'
}

list_candidates() {
  local found=false
  for d in /dev/ttyUSB* /dev/ttyACM*; do
    [[ -e "$d" ]] || continue
    found=true
    echo "=== $d ==="
    udevadm info -q property -n "$d" | grep -E "ID_VENDOR_ID|ID_MODEL_ID|ID_SERIAL_SHORT|ID_PATH=" || true
    echo
  done
  if [[ "$found" == false ]]; then
    log "No /dev/ttyUSB* or /dev/ttyACM* devices found."
  fi
}

build_rule() {
  local dev="$1"
  local link="$2"
  local vendor model serial path
  vendor="$(get_prop "$dev" "ID_VENDOR_ID")"
  model="$(get_prop "$dev" "ID_MODEL_ID")"
  serial="$(get_prop "$dev" "ID_SERIAL_SHORT")"
  path="$(get_prop "$dev" "ID_PATH")"

  if [[ -n "$vendor" && -n "$model" && -n "$serial" ]]; then
    echo "SUBSYSTEM==\"tty\", ENV{ID_VENDOR_ID}==\"$vendor\", ENV{ID_MODEL_ID}==\"$model\", ENV{ID_SERIAL_SHORT}==\"$serial\", SYMLINK+=\"$link\", GROUP=\"dialout\", MODE=\"0660\""
    return 0
  fi

  if [[ -n "$path" ]]; then
    echo "SUBSYSTEM==\"tty\", ENV{ID_PATH}==\"$path\", SYMLINK+=\"$link\", GROUP=\"dialout\", MODE=\"0660\""
    return 0
  fi

  die "Cannot derive udev identity keys for $dev (no ID_SERIAL_SHORT/ID_PATH)."
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --device)
        LIDAR_DEV="${2:-}"
        shift 2
        ;;
      --link)
        LIDAR_LINK="${2:-}"
        shift 2
        ;;
      --rule-file)
        RULE_FILE="${2:-}"
        shift 2
        ;;
      --list)
        LIST_ONLY=true
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown argument: $1"
        ;;
    esac
  done
}

validate_device() {
  local d="$1"
  [[ -n "$d" ]] || die "Device argument is empty."
  [[ -e "$d" ]] || die "Device does not exist: $d"
  [[ -c "$d" ]] || die "Not a character device: $d"
}

main() {
  parse_args "$@"

  if [[ "$LIST_ONLY" == true ]]; then
    list_candidates
    exit 0
  fi

  [[ -n "$LIDAR_DEV" ]] || die "--device is required (or use --list)."
  validate_device "$LIDAR_DEV"

  local lidar_rule tmp_rule
  lidar_rule="$(build_rule "$LIDAR_DEV" "$LIDAR_LINK")"

  tmp_rule="$(mktemp)"
  cat >"$tmp_rule" <<EOF
# Generated by setup_lidar_udev.sh
# Lidar source: $LIDAR_DEV

$lidar_rule
EOF

  log "Generated rule:"
  cat "$tmp_rule"
  echo

  log "Installing rule to: $RULE_FILE"
  run_root mkdir -p "$(dirname "$RULE_FILE")"
  run_root install -m 0644 "$tmp_rule" "$RULE_FILE"
  rm -f "$tmp_rule"

  log "Reloading udev rules"
  run_root udevadm control --reload-rules
  run_root udevadm trigger --subsystem-match=tty

  log "Done. Verify symlink:"
  ls -l "/dev/$LIDAR_LINK" 2>/dev/null || \
    log "Symlink not visible yet. Reconnect lidar USB and run: ls -l /dev/$LIDAR_LINK"
}

main "$@"
