#!/usr/bin/env bash
set -euo pipefail

RULE_FILE="/etc/udev/rules.d/99-robot-motor.rules"
LEFT_LINK="ttyMotorLeft"
RIGHT_LINK="ttyMotorRight"
LEFT_DEV=""
RIGHT_DEV=""
LIST_ONLY=false

usage() {
  cat <<'EOF'
Usage:
  setup_motor_udev.sh --list
  setup_motor_udev.sh --left /dev/ttyUSB0 --right /dev/ttyUSB1 [options]

Options:
  --left <device>         Left motor serial device (e.g. /dev/ttyUSB0)
  --right <device>        Right motor serial device (e.g. /dev/ttyUSB1)
  --left-link <name>      udev symlink name for left motor (default: ttyMotorLeft)
  --right-link <name>     udev symlink name for right motor (default: ttyMotorRight)
  --rule-file <path>      udev rules output path (default: /etc/udev/rules.d/99-robot-motor.rules)
  --list                  Print candidate tty devices and properties
  -h, --help              Show this help

Notes:
  - Rule priority: ID_VENDOR_ID + ID_MODEL_ID + ID_SERIAL_SHORT
    Fallback: ID_PATH (when ID_SERIAL_SHORT is not available)
  - The script applies rules via sudo if needed.
EOF
}

die() {
  echo "[ERROR] $*" >&2
  exit 1
}

log() {
  echo "[INFO] $*"
}

run_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

get_prop() {
  local dev="$1"
  local key="$2"
  udevadm info -q property -n "$dev" | awk -F= -v k="$key" '$1 == k {print $2; exit}'
}

list_candidates() {
  local found=false
  for d in /dev/ttyUSB* /dev/ttyACM*; do
    [[ -e "$d" ]] || continue
    found=true
    echo "=== $d ==="
    udevadm info -q property -n "$d" | grep -E "ID_VENDOR_ID|ID_MODEL_ID|ID_SERIAL_SHORT|ID_PATH=" || true
    echo
  done
  if [[ "$found" == false ]]; then
    log "No /dev/ttyUSB* or /dev/ttyACM* devices found."
  fi
}

build_rule() {
  local dev="$1"
  local link="$2"
  local vendor model serial path
  vendor="$(get_prop "$dev" "ID_VENDOR_ID")"
  model="$(get_prop "$dev" "ID_MODEL_ID")"
  serial="$(get_prop "$dev" "ID_SERIAL_SHORT")"
  path="$(get_prop "$dev" "ID_PATH")"

  if [[ -n "$vendor" && -n "$model" && -n "$serial" ]]; then
    echo "SUBSYSTEM==\"tty\", ENV{ID_VENDOR_ID}==\"$vendor\", ENV{ID_MODEL_ID}==\"$model\", ENV{ID_SERIAL_SHORT}==\"$serial\", SYMLINK+=\"$link\", GROUP=\"dialout\", MODE=\"0660\""
    return 0
  fi

  if [[ -n "$path" ]]; then
    echo "SUBSYSTEM==\"tty\", ENV{ID_PATH}==\"$path\", SYMLINK+=\"$link\", GROUP=\"dialout\", MODE=\"0660\""
    return 0
  fi

  die "Cannot derive udev identity keys for $dev (no ID_SERIAL_SHORT/ID_PATH)."
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --left)
        LEFT_DEV="${2:-}"
        shift 2
        ;;
      --right)
        RIGHT_DEV="${2:-}"
        shift 2
        ;;
      --left-link)
        LEFT_LINK="${2:-}"
        shift 2
        ;;
      --right-link)
        RIGHT_LINK="${2:-}"
        shift 2
        ;;
      --rule-file)
        RULE_FILE="${2:-}"
        shift 2
        ;;
      --list)
        LIST_ONLY=true
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown argument: $1"
        ;;
    esac
  done
}

validate_device() {
  local d="$1"
  [[ -n "$d" ]] || die "Device argument is empty."
  [[ -e "$d" ]] || die "Device does not exist: $d"
  [[ -c "$d" ]] || die "Not a character device: $d"
}

main() {
  parse_args "$@"

  if [[ "$LIST_ONLY" == true ]]; then
    list_candidates
    exit 0
  fi

  [[ -n "$LEFT_DEV" ]] || die "--left is required (or use --list)."
  [[ -n "$RIGHT_DEV" ]] || die "--right is required (or use --list)."
  validate_device "$LEFT_DEV"
  validate_device "$RIGHT_DEV"

  local left_rule right_rule tmp_rule
  left_rule="$(build_rule "$LEFT_DEV" "$LEFT_LINK")"
  right_rule="$(build_rule "$RIGHT_DEV" "$RIGHT_LINK")"

  tmp_rule="$(mktemp)"
  cat >"$tmp_rule" <<EOF
# Generated by setup_motor_udev.sh
# Left source:  $LEFT_DEV
# Right source: $RIGHT_DEV

$left_rule
$right_rule
EOF

  log "Generated rules:"
  cat "$tmp_rule"
  echo

  log "Installing rules to: $RULE_FILE"
  run_root mkdir -p "$(dirname "$RULE_FILE")"
  run_root install -m 0644 "$tmp_rule" "$RULE_FILE"
  rm -f "$tmp_rule"

  log "Reloading udev rules"
  run_root udevadm control --reload-rules
  run_root udevadm trigger --subsystem-match=tty

  log "Done. Verify symlinks:"
  ls -l "/dev/$LEFT_LINK" "/dev/$RIGHT_LINK" 2>/dev/null || \
    log "Symlink not visible yet. Reconnect adapters and run: ls -l /dev/$LEFT_LINK /dev/$RIGHT_LINK"
}

main "$@"
